#! python

input_assessments = open( 'output/3-species19-all_sequences-all_assessments-PFAM_ok', 'r' )
output_superrelaxed = open( 'output/4-species19-secretome-pfam_ok-superrelaxed', 'w' )
output_relaxed = open( 'output/4-species19-secretome-pfam_ok-relaxed', 'w' )
output_strict = open( 'output/4-species19-secretome-pfam_ok-strict', 'w' )
output_superstrict = open( 'output/4-species19-secretome-pfam_ok-superstrict', 'w' )
output_deeploc = open( 'output/4-species19-secretome-pfam_ok-deeploc', 'w' )
output_deeptmhmm = open( 'output/4-species19-secretome-pfam_ok-deeptmhmm', 'w' )
output_signalp =  open( 'output/4-species19-secretome-pfam_ok-signalp', 'w' )

# Genus   Identifiert   Superrelaxed Relaxed Strict  Superstrict     DeepLoc DeepTMHMM       SignalP DeepLoc2_SM     DeepLoc2_SP     DeepLoc2_TM     DeepTMHMM_SP    DeepTMHMM_TM    SignalP6_SP     Metapredict_IDR MobiDBLite_IDR
first_line = False
for next_line in input_assessments:
    if first_line == False:
        first_line = True
    else:
        info = next_line.split( '\t' )
        superrelaxed = info[ 2 ]
        relaxed = info[ 3 ]
        strict = info[ 4 ]
        superstrict = info[ 5 ]
        deeploc = info[ 6 ]
        deeptmhmm = info[ 7 ]
        signalp = info[ 8 ]

        if len( superrelaxed.split( 'ES_' ) ) > 1:
            output_superrelaxed.write( next_line )
        if len( relaxed.split( 'ES_' ) ) > 1:
            output_relaxed.write( next_line )
        if len( strict.split( 'ES_' ) ) > 1:
            output_strict.write( next_line )
        if len( superstrict.split( 'ES_' ) ) > 1:
            output_superstrict.write( next_line )
        if len( deeploc.split( 'ES_' ) ) > 1:
            output_deeploc.write( next_line )
        if len( deeptmhmm.split( 'ES_' ) ) > 1:
            output_deeptmhmm.write( next_line )
        if len( signalp.split( 'ES_' ) ) > 1:
            output_signalp.write( next_line )
            
input_assessments.close()
output_superrelaxed.close()
output_relaxed.close()
output_strict.close()
output_superstrict.close()
output_deeploc.close()
output_deeptmhmm.close()
output_signalp.close()
