#! python

input_leonid = open( '/scratch/eric/projects/aplysia/secretome/cgs-manual/leonid_ssp709/output/rgs_leonid_ssp709-clean-20230508_1302.fasta', 'r' )

input_secretome_relaxed = open( 'output/2-species19-secretome-no_pfam-relaxed', 'r' )
input_secretome_relaxed_pfam_ok = open( 'output/4-species19-secretome-pfam_ok-relaxed', 'r' )
output_leonid_ssp709_X_relaxed_no_pfam = open( 'output/6-leonid_ssp709_X_relaxed_no_pfam', 'w' )
output_relaxed_X_leonid_ssp709_no_pfam = open( 'output/6-relaxed_X_leonid_ssp709_no_pfam', 'w' )

leonid_ssp709s = []
for next_line in input_leonid:
    if next_line[ 0 ] == '>':
        leonid_ssp709 = next_line.split( '-' )[ 2 ]
        glocid = 'Aplysia___' + leonid_ssp709
        leonid_ssp709s.append( glocid )

# relaxed no_Pfam X leonid_ssp709
relaxed_no_pfam = {}
first_line = False
for next_line in input_secretome_relaxed:
    genus = next_line.split( '\t' )[ 0 ]
    locid = next_line.split( '\t' )[ 1 ]
    glocid = genus + '___' + locid
    relaxed_no_pfam[ glocid ] = next_line[ :-1 ]
    if first_line == False:
        first_line = True
        header = next_line

for next_glocid in leonid_ssp709s:
    if next_glocid in relaxed_no_pfam.keys():
        output = 'Keeper' + '\t' + relaxed_no_pfam[ next_glocid ] +  '\n'
    else:
        next_locid = next_glocid.split( '___' )[ -1 ]
        output = 'Aplysia' + '\t' + next_locid + '\t'
        for next_element in header.split( '\t' )[ 2: ]:
            output = output + 'NA' + '\t'
        output = 'Dropper' + '\t' + output +  '\n'
    output_leonid_ssp709_X_relaxed_no_pfam.write( output )

for next_glocid in relaxed_no_pfam.keys():
    if len( next_glocid.split( 'Aplysia' ) ) > 1:
        if next_glocid in leonid_ssp709s:
            output = 'Keeper' + '\t' + relaxed_no_pfam[ next_glocid ] +  '\n'
        else:
            output = 'Dropper' + '\t' + relaxed_no_pfam[ next_glocid ] +  '\n'
        output_relaxed_X_leonid_ssp709_no_pfam.write( output )
    
output_leonid_ssp709_X_relaxed_no_pfam.close()
output_relaxed_X_leonid_ssp709_no_pfam.close()
        
input_leonid.close()
input_secretome_relaxed.close() 
input_secretome_relaxed_pfam_ok.close() 
