#! python

input_leonid = open( '/scratch/eric/projects/aplysia/secretome/cgs-manual/leonid_ssp204/output/rgs_leonid_ssp204-clean-20230508_1215.fasta', 'r' )

input_secretome_signalp = open( 'output/2-species19-secretome-no_pfam-signalp', 'r' )
input_secretome_signalp_pfam_ok = open( 'output/4-species19-secretome-pfam_ok-signalp', 'r' )
output_leonid_ssp204_X_signalp_no_pfam = open( 'output/11-leonid_ssp204_X_signalp_no_pfam', 'w' )
output_signalp_X_leonid_ssp204_no_pfam = open( 'output/11-signalp_X_leonid_ssp204_no_pfam', 'w' )

leonid_ssp204s = []
for next_line in input_leonid:
    if next_line[ 0 ] == '>':
        leonid_ssp204 = next_line.split( '-' )[ 2 ]
        glocid = 'Aplysia___' + leonid_ssp204
        leonid_ssp204s.append( glocid )

# signalp no_Pfam X leonid_ssp204
signalp_no_pfam = {}
first_line = False
for next_line in input_secretome_signalp:
    genus = next_line.split( '\t' )[ 0 ]
    locid = next_line.split( '\t' )[ 1 ]
    glocid = genus + '___' + locid
    signalp_no_pfam[ glocid ] = next_line[ :-1 ]
    if first_line == False:
        first_line = True
        header = next_line

for next_glocid in leonid_ssp204s:
    if next_glocid in signalp_no_pfam.keys():
        output = 'Keeper' + '\t' + signalp_no_pfam[ next_glocid ] +  '\n'
    else:
        next_locid = next_glocid.split( '___' )[ -1 ]
        output = 'Aplysia' + '\t' + next_locid + '\t'
        for next_element in header.split( '\t' )[ 2: ]:
            output = output + 'NA' + '\t'
        output = 'Dropper' + '\t' + output +  '\n'
    output_leonid_ssp204_X_signalp_no_pfam.write( output )


for next_glocid in signalp_no_pfam.keys():
    if len( next_glocid.split( 'Aplysia' ) ) > 1:
        if next_glocid in leonid_ssp204s:
            output = 'Keeper' + '\t' + signalp_no_pfam[ next_glocid ] +  '\n'
        else:
            output = 'Dropper' + '\t' + signalp_no_pfam[ next_glocid ] +  '\n'
        output_signalp_X_leonid_ssp204_no_pfam.write( output )
    
output_leonid_ssp204_X_signalp_no_pfam.close()
output_signalp_X_leonid_ssp204_no_pfam.close()
        
input_leonid.close()
input_secretome_signalp.close() 
input_secretome_signalp_pfam_ok.close() 
