#! python

input_leonid = open( '/scratch/eric/projects/aplysia/secretome/cgs-manual/leonid_ssp204/output/rgs_leonid_ssp204-clean-20230508_1215.fasta', 'r' )
input_secretome_relaxed_pfam_ok = open( 'output/4-species19-secretome-pfam_ok-relaxed', 'r' )
output_leonid_ssp204_X_relaxed_pfam_ok = open( 'output/13-leonid_ssp204_X_relaxed_pfam_ok', 'w' )
output_relaxed_X_leonid_ssp204_pfam_ok = open( 'output/13-relaxed_X_leonid_ssp204_pfam_ok', 'w' )

leonid_ssp204s = []
for next_line in input_leonid:
    if next_line[ 0 ] == '>':
        leonid_ssp204 = next_line.split( '-' )[ 2 ]
        glocid = 'Aplysia___' + leonid_ssp204
        leonid_ssp204s.append( glocid )

# relaxed Pfam_ok X leonid_ssp204
relaxed_pfam_ok = {}
first_line = False
for next_line in input_secretome_relaxed_pfam_ok:
    genus = next_line.split( '\t' )[ 0 ]
    locid = next_line.split( '\t' )[ 1 ]
    glocid = genus + '___' + locid
    relaxed_pfam_ok[ glocid ] = next_line[ :-1 ]
    if first_line == False:
        first_line = True
        header = next_line

for next_glocid in leonid_ssp204s:
    if next_glocid in relaxed_pfam_ok.keys():
        output = 'Keeper' + '\t' + relaxed_pfam_ok[ next_glocid ] +  '\n'
    else:
        next_locid = next_glocid.split( '___' )[ -1 ]
        output = 'Aplysia' + '\t' + next_locid + '\t'
        for next_element in header.split( '\t' )[ 2: ]:
            output = output + 'NA' + '\t'
        output = 'Dropper' + '\t' + output +  '\n'
    output_leonid_ssp204_X_relaxed_pfam_ok.write( output )

for next_glocid in relaxed_pfam_ok.keys():
    if len( next_glocid.split( 'Aplysia' ) ) > 1:
        if next_glocid in leonid_ssp204s:
            output = 'Keeper' + '\t' + relaxed_pfam_ok[ next_glocid ] +  '\n'
        else:
            output = 'Dropper' + '\t' + relaxed_pfam_ok[ next_glocid ] +  '\n'
        output_relaxed_X_leonid_ssp204_pfam_ok.write( output )
    
output_leonid_ssp204_X_relaxed_pfam_ok.close()
output_relaxed_X_leonid_ssp204_pfam_ok.close()
input_leonid.close()
input_secretome_relaxed_pfam_ok.close()
