#! /bin/bash
# GIGANTIC gene trees script

sed -e 's/-/_/g' ../../../homologs/blastp/output/17-AGS_blastp-rgs-hgnc-human-transcription_factor_zinc_finger_family_X_species19.aa > output/1-AGS-hgnc-transcription_factor_zinc_finger_C2H2_family-blastp_X_species19.aa
