#! /bin/bash
# GIGANTIC gene trees script

sed -e 's/U/X/g' output/1-AGS-hgnc-transcription_factor_zinc_finger_C2H2_family-blastp_X_species19.aa  > output/2-AGS-hgnc-transcription_factor_zinc_finger_C2H2_family-family-blastp_X_species19.aa
