#! python

input_list = open( 'output/4-list-blast-reports', 'r' )
output_mollusca = open( 'output/4-list-mollusca-all', 'w' )
output_ephyneura = open( 'output/4-list-ethyneura-all', 'w' )
output_gastropoda = open( 'output/4-list-gastropoda-all', 'w' )
output_bivalvia = open( 'output/4-list-bivalvia-all', 'w' )
output_cephalopoda = open( 'output/4-list-cephalopoda-all', 'w' )
output_models = open( 'output/4-list-models-all', 'w' )
output_lophotrochozoa = open( 'output/4-list-lophotrochozoa-all', 'w' )
output_bilateria = open( 'output/4-list-bilateria-all', 'w' )
output_protostomia = open( 'output/4-list-protostomia-all', 'w' )
output_conchifera = open( 'output/4-list-conchifera-all', 'w' )

mollusca_all = ['Acanthopleura', 'Mizuhopecten', 'Crassostrea', 'Cyclina', 'Lottia', 'Gigantopelta', 'Pomacea', 'Aplysia', 'Elysia', 'Achatina', 'Nautilus', 'Argonauta',  'Octopus' ]
ephyneura_all = [ 'Aplysia', 'Elysia', 'Achatina' ]
gastropoda_all = [ 'Lottia', 'Gigantopelta', 'Pomacea', 'Aplysia', 'Elysia', 'Achatina' ]
bivalvia_all = [ 'Cyclina', 'Mizuhopecten', 'Crassostrea' ]
cephalopod_all = [ 'Octopus', 'Argonauta', 'Nautilus' ]
lophotrochozoa_all = [ 'Lingula', 'Capitella', 'Phoronis', 'Acanthopleura', 'Mizuhopecten', 'Crassostrea', 'Cyclina', 'Lottia', 'Gigantopelta', 'Pomacea', 'Aplysia', 'Elysia', 'Achatina', 'Nautilus', 'Argonauta', 'Octopus' ]
model_all = [ 'Homo', 'Drosophila', 'Caenorhabditis', 'Aplysia' ]
bilateria_all = [ 'Homo', 'Lingula', 'Capitella', 'Phoronis', 'Acanthopleura', 'Mizuhopecten', 'Crassostrea', 'Cyclina', 'Lottia', 'Gigantopelta', 'Pomacea', 'Aplysia', 'Elysia', 'Achatina', 'Nautilus', 'Argonauta', 'Octopus' ]
protostomia_all = [ 'Drosophila', 'Caenorhabditis', 'Aplysia' ]
conchifera_all = [ 'Mizuhopecten', 'Crassostrea', 'Cyclina', 'Lottia', 'Gigantopelta', 'Pomacea', 'Aplysia', 'Elysia', 'Achatina', 'Nautilus', 'Argonauta',  'Octopus' ]

# output/3-blast-report-Acanthopleura-granulata_x_Aplysia-californica

for next_line in input_list:

    info = next_line[ :-1 ].split( '_x_' )
    info_gspp_1 = info[ 0 ].split( '-' )
    genus_1 = info_gspp_1[ -2 ]
    info_gspp_2 = info[ -1 ].split( '-' )
    genus_2 = info_gspp_2[ 0 ]
    
    if ( genus_1 in mollusca_all ) and ( genus_2 in mollusca_all ):
        output_mollusca.write( next_line )
    if ( genus_1 in ephyneura_all ) and ( genus_2 in ephyneura_all ):
        output_ephyneura.write( next_line )
    if ( genus_1 in gastropoda_all ) and ( genus_2 in gastropoda_all ):
        output_gastropoda.write( next_line )
    if ( genus_1 in bivalvia_all ) and ( genus_2 in bivalvia_all ):
        output_bivalvia.write( next_line )
    if ( genus_1 in cephalopod_all ) and ( genus_2 in cephalopod_all ):
        output_cephalopoda.write( next_line )
    if ( genus_1 in model_all ) and ( genus_2 in model_all ):
        output_models.write( next_line )
    if ( genus_1 in lophotrochozoa_all ) and ( genus_2 in lophotrochozoa_all ):
        output_lophotrochozoa.write( next_line )
    if ( genus_1 in bilateria_all ) and ( genus_2 in bilateria_all ):
        output_bilateria.write( next_line )
    if ( genus_1 in protostomia_all ) and ( genus_2 in protostomia_all ):
        output_protostomia.write( next_line )
    if ( genus_1 in conchifera_all ) and ( genus_2 in conchifera_all ):
        output_conchifera.write( next_line )
    else:
        pass

input_list.close()
output_mollusca.close()
output_ephyneura.close()
output_gastropoda.close()
output_bivalvia.close()
output_cephalopoda.close()
output_models.close()
output_protostomia.close()
output_conchifera.close()
output_bilateria.close()
output_lophotrochozoa.close()
