#! python

input_fastas = open( 'output/4-list-fastas','r')
for next_fasta in input_fastas:

    fasta_path = next_fasta[ :-1 ]
    input_fasta = open( fasta_path, 'r' )

    fasta = next_fasta[ :-1 ].split( '/' )[ -1 ]
    output_filename = 'projectdb-fastas/' + fasta
    output_fasta = open( output_filename, 'w' )
    
    header_seq = {}
    for next_line in input_fasta:

        if next_line[ 0 ] == '>':

            header = next_line
            header_seq[ header ] = ''

        else:

            sequence = next_line[ :-1 ]
            header_seq[ header ] = header_seq[ header ] + sequence

    for next_header in header_seq.keys():

        header = next_header
        sequence = header_seq[ header ] + '\n'
        output = header + sequence
        output_fasta.write( output )

    input_fasta.close()
    output_fasta.close()
input_fastas.close()
