#! python

input_fastas = open( 'output/6-list-fastas', 'r' )
output_commands = open( '008-busco-metazoa-otherdb-CONDA', 'w' )


for next_line in input_fastas:

    fasta = next_line[ :-1 ]
    phylogenome = fasta.split( '/' )[ -1 ]
    info_1 = phylogenome.split( '-' )
    name_1 = '-'.join( info_1[ 1: ] )
    info_2 = name_1.split( '.' )
    name_2 = '.'.join( info_2[ :-1 ] )
    
    output = 'busco  --config 008-busco-metazoa.ini -i ' + fasta + ' -o busco_metazoa-' + name_2 + ' &&\n'
    output_commands.write( output )

output = 'echo\n'
output_commands.write( output )

input_fastas.close()
output_commands.close()
