#! python

input_fastas = open( 'output/2-list-fastas', 'r' )
output_map = open( 'output/3-map-projectdb-headers-to-old-headers', 'w' )

counter = 0
for next_fasta in input_fastas:

    fasta_path = next_fasta[ :-1 ]
    input_fasta = open( fasta_path, 'r' )

    fasta = fasta_path.split( '/' )[ -1 ]
    phyloshort = '-'.join( fasta.split( '-' )[ :-2 ] )
    projectdb_fasta = 'output/3-output/projectdb-' + fasta 
    output_fasta = open( projectdb_fasta, 'w' )
        
    for next_line in input_fasta:

        if next_line[ 0 ] == '>':

            counter = counter + 1
            
            info = next_line[ 1: ].split( '-' )
            header = '>' + phyloshort + '-pdb' + str( counter ).zfill(10) + '\n'
            output_fasta.write( header )

            output = header [ 1:-1 ] + '\t' + next_line[ 1: ]
            output_map.write( output )
            
        else:

            sequence = next_line
            output_fasta.write( sequence )

    input_fasta.close()
    output_fasta.close()

input_fastas.close()
output_map.close()
