#! python
# Interproscan script

# /home/eedsinger/software/interproscan/interproscan-5.48-83.0/interproscan.sh --applications Pfam --input  ../species311/species311-fastas/*Acanthopleura-granulata*aa --cpu 45 --disable-precalc                                      

input_fastas = open( '1-list-fastas', 'r' )
output_command = open('003-interproscan-pfam-only', 'w')

for next_fasta in input_fastas:

    fasta = next_fasta[ :-1 ]
    info = fasta.split( '/' )[ -1 ]
    info_2 = info.split( '-' )
    gspp = info_2[ 5 ] + ' ' + info_2[ 6 ]

    output = '/home/eedsinger/software/interproscan/interproscan-5.48-83.0/interproscan.sh --applications Pfam MobiDBLite --input ' + fasta + ' --cpu 75 --disable-precalc \n'
    output_command.write( output )

input_fastas.close()
output_command.close()
