#! python

input_list = open( 'output/4-list-blast-reports', 'r' )
output_mollusca = open( 'output/4-list-mollusca-lite', 'w' )
output_ephyneura = open( 'output/4-list-ethyneura-lite', 'w' )
output_gastropoda = open( 'output/4-list-gastropoda-lite', 'w' )
output_bivalvia = open( 'output/4-list-bivalvia-lite', 'w' )
output_cephalopoda = open( 'output/4-list-cephalopoda-lite', 'w' )
output_models = open( 'output/4-list-models-lite', 'w' )
output_lophotrochozoa = open( 'output/4-list-lophotrochozoa-lite', 'w' )
output_bilateria = open( 'output/4-list-bilateria-lite', 'w' )
output_protostomia = open( 'output/4-list-protostomia-lite', 'w' )
output_conchifera = open( 'output/4-list-conchifera-lite', 'w' )

mollusca_core = ['Acanthopleura', 'Mizuhopecten', 'Aplysia', 'Octopus' ]
ephyneura_core = [ 'Aplysia', 'Elysia', 'Achatina' ]
gastropoda_core = [ 'Lottia', 'Gigantopelta', 'Pomacea', 'Aplysia' ]
bivalvia_core = [ 'Cyclina', 'Mizuhopecten', 'Crassostrea' ]
cephalopod_core = [ 'Octopus', 'Argonauta', 'Nautilus' ]
lophotrochozoa_core = [ 'Aplysia', 'Lingula', 'Capitella', 'Phoronis' ]
model_core = [ 'Homo', 'Drosophila', 'Caenorhabditis', 'Aplysia' ]
bilateria_core = [ 'Homo', 'Drosophila', 'Caenorhabditis', 'Aplysia', 'Lingula', 'Capitella', 'Phoronis' ]
protostomia_core = [ 'Drosophila', 'Caenorhabditis', 'Aplysia' ]
conchifera_core = [ 'Octopus', 'Argonauta', 'Nautilus', 'Cyclina', 'Mizuhopecten', 'Crassostrea', 'Lottia', 'Gigantopelta', 'Aplysia' ]

# output/3-blast-report-Acanthopleura-granulata_x_Aplysia-californica

for next_line in input_list:

    info = next_line[ :-1 ].split( '_x_' )
    info_gspp_1 = info[ 0 ].split( '-' )
    genus_1 = info_gspp_1[ -2 ]
    info_gspp_2 = info[ -1 ].split( '-' )
    genus_2 = info_gspp_2[ 0 ]
    
    if ( genus_1 in mollusca_core ) and ( genus_2 in mollusca_core ):
        output_mollusca.write( next_line )
    if ( genus_1 in ephyneura_core ) and ( genus_2 in ephyneura_core ):
        output_ephyneura.write( next_line )
    if ( genus_1 in gastropoda_core ) and ( genus_2 in gastropoda_core ):
        output_gastropoda.write( next_line )
    if ( genus_1 in bivalvia_core ) and ( genus_2 in bivalvia_core ):
        output_bivalvia.write( next_line )
    if ( genus_1 in cephalopod_core ) and ( genus_2 in cephalopod_core ):
        output_cephalopoda.write( next_line )
    if ( genus_1 in model_core ) and ( genus_2 in model_core ):
        output_models.write( next_line )
    if ( genus_1 in lophotrochozoa_core ) and ( genus_2 in lophotrochozoa_core ):
        output_lophotrochozoa.write( next_line )
    if ( genus_1 in bilateria_core ) and ( genus_2 in bilateria_core ):
        output_bilateria.write( next_line )
    if ( genus_1 in protostomia_core ) and ( genus_2 in protostomia_core ):
        output_protostomia.write( next_line )
    if ( genus_1 in conchifera_core ) and ( genus_2 in conchifera_core ):
        output_conchifera.write( next_line )
    else:
        pass

input_list.close()
output_mollusca.close()
output_ephyneura.close()
output_gastropoda.close()
output_bivalvia.close()
output_cephalopoda.close()
output_models.close()
output_protostomia.close()
output_conchifera.close()
output_bilateria.close()
output_lophotrochozoa.close()
