#! /bin/bash

ls -1 /scratch/eric/projects/aplysia/secretome/cgs-annotation/output/2-species19-secretome-* > output/1-annotation-secretomes-pfam_absent
ls -1 /scratch/eric/projects/aplysia/secretome/cgs-annotation/output/4-species19-secretome-* > output/1-annotation-secretomes-pfam_ok

ls -1 /scratch/eric/projects/aplysia/secretome/cgs-blast/leonid_ssp204/output/30-clusters-Species19-leonid_ssp204-blastp-evalue* > output/1-blast-secretomes
