#! python

input_subsets = open( 'output/109-list-nohit-fasta-subsets', 'r' )
output_blastp = open( '0111-blastp-nohit-substs_X_nr', 'w' )

# blastp -query ../../projectdbs/species19/Metazoa-Mollusca-Gastropoda-Aplysiida-Aplysiidae-Aplysia-californica-6500-T1.aa -db ./nr -evalue 1e-5 -outfmt "6 qseqid staxids sseqid sgi sacc evalue" -out output/101-blast-report-aplysia_X_nr -max_target_seqs 10 -max_hsps 1 -num_threads 32 -negative_taxids 6500

# output-fasta-subsets/108-nohits-fasta-1
# output-fasta-subsets/108-nohits-fasta-1

for next_hog in input_subsets:
    info = next_hog[ :-1 ].split( '/' )
    hog_subset = info [ -1 ].split( '-' )
    hog_subset_count = hog_subset[ -1 ]
    
    
    output = 'blastp -query ' + next_hog[ :-1 ] +  ' -db ./nr -evalue 1e-5 -outfmt "6 qseqid staxids sseqid sgi sacc evalue" -out output-blast-reports/111-blast-report-aplysia-nohit-sequences-' + hog_subset_count + '_X_nr -max_target_seqs 10 -max_hsps 1 -num_threads 1 -negative_taxids 6500 &\n'
    output_blastp.write( output )

input_subsets.close()
output_blastp.close()
