#! python
input_leonid = open( 'input/leonid-signal-locid-names.tsv', 'r' )
output_leonid = open( 'input/leo', 'w' )

for next_line in input_leonid:
    info = next_line.split( '\t' )
    locid = info[ 0 ]
    name = info[ 1 ] 
    output = locid + '\t' + name + '\n'
    output_leonid.write( output )

input_leonid.close()
output_leonid.close()
