#! python
# GIGANTIC ProjectDB

###User Input###

pathfile = open( 'output/3-list-gffs-Nematostella_vectensis', 'r') # User modified

### No need to modify ###
for next_path in pathfile:

    path = next_path[ :-1 ]

    filename = '.'.join( path.split('/')[-1].split('.')[:-1] )
    gspp = path.split( '/' )[ 0 ] 
    folder = path
    
    # Leave a record
    print( 'processing', filename )

    # Output files
    output_parsing = open( 'output/4-output/4-map-gff-' + filename, 'w' )
    output_error = open( 'output/4-output/4-error-' + filename,'w')
    
    # Initialize variables
    all_genes = {}
    
    # Parsing lines in GFF
    inputGFF = open( path , 'r' )

    for next_line in inputGFF:

        #### chrUn2  transdecoder    gene    5660    11862   .       -       .       ID=NV2g025879000.1;geneID=NV2.25879;Name=xpo4;Note=Exportin-4 (Danio rerio OX%3D7955);Alias=NV2.25879
        
        # Skip commented lines and empty lines
        if ( next_line[ 0 ] != '#' ) and ( len(next_line) > 1 ):

            # Parse tab delimited lines
            data = next_line[ : -1 ].split( '\t' )
            seqid = data[ 0 ] #scaffold/landmark id
            source = data[ 1 ] # ex: FlyBase, Genbank, etc.
            type_info = data[ 2 ] #gene, mRNA,  CDS
            start = data[ 3 ] #coordinate start
            end = data[ 4 ] #coordinate end
            score = data[ 5 ] #typically e-value
            strand = data[ 6 ] #+/-
            phase = data[ 7 ] #CDS info: nucleotide codon frame starts on
            attributes = data[ 8 ] #ID, Name, Alias, Parent, Target, Gap, Derives_from, Note, Dbxref, Ontology_term, Is_circular
                
            #Split attributes column into tag value pairs: ",=;"
            tags = attributes.split( ';' )
            while "" in tags:
                tags.remove( "" )
      
            ###Process entries of type mRNA to get corresponding gene identifier

            for tag_value_pair in tags:

                taginfo = tag_value_pair.split( '=' )
                tag = taginfo[ 0 ]
                identifier = taginfo[ 1 ]

                if type_info == 'gene':
                    gene = identifier
                    all_genes[ gene ] = []
    
                elif type_info == 'mRNA':
                    rna = identifier
                    
                elif type_info == 'CDS':
                    rna_cds = rna + '\t' + cds
                            
                    if rna_cds in all_genes[ gene ]:
                        pass
                    else:
                        all_genes[ gene ].append( rna_cds )

                else:
                    cds = identifier
                    output_error.write( 'check out ' + identifier + '\n' )
                            
    inputGFF.close()

    for next_gene in all_genes:
        
        for next_rna in all_genes[ next_gene ]:
            output_parsing.write( gspp + '\t' + folder + '\t' + next_gene + '\t' + next_rna + '\n')

    output_parsing.close()
    output_error.close()

pathfile.close()
