#! /bin/bash
# GIGANTIC ProjectDB

#/mnlsc/data/eedsinger/databases/gigantic/omg/genomedb/gdb2/animals/2021-nov/1-downloaded/downloaded/*
#/mnlsc/data/eedsinger/databases/gigantic/omg/genomedb/gdb2/animals/2021-nov/1-downloaded/0-map-ALL-gspp-db-source_genome_id

mkdir output
mkdir output/4-output
mkdir output/5-output

mkdir phylogenomes
mkdir phylonames

mkdir output/15-output

cp 001-metazoaALL-ready-to-download-set1.tsv 001-list-othersdb-source-info.tsv


#Make a list of paths to gffs
#ls -1 /mnlsc/data/eedsinger/databases/gigantic/omg/genomedb/gdb2/animals/2021-nov/1-downloaded/downloaded/*/gff/* > output/0-list-gffs

#Make a list of paths to proteomes (aa)
#ls -1 /mnlsc/data/eedsinger/databases/gigantic/omg/genomedb/gdb2/animals/2021-nov/1-downloaded/downloaded/*/aa/* > output/0-list-fastas


