#! /bin/bash
# GIGANTIC ProjectDB

mkdir Arthropoda-Polistes-fuscatus &&
cd Arthropoda-Polistes-fuscatus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/010/416/935/GCF_010416935.1_CU_Pfus_HIC/GCF_010416935.1_CU_Pfus_HIC_protein.faa.gz -O Arthropoda-Polistes-fuscatus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/010/416/935/GCF_010416935.1_CU_Pfus_HIC/GCF_010416935.1_CU_Pfus_HIC_genomic.gff.gz -O Arthropoda-Polistes-fuscatus.gff.gz &&
cd .. &&
mkdir Arthropoda-Galleria-mellonella &&
cd Arthropoda-Galleria-mellonella &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/640/425/GCF_003640425.2_ASM364042v2/GCF_003640425.2_ASM364042v2_protein.faa.gz -O Arthropoda-Galleria-mellonella.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/731/565/GCF_009731565.1_Dplex_v4/GCF_009731565.1_Dplex_v4_genomic.gff.gz -O Arthropoda-Galleria-mellonella.gff.gz &&
cd .. &&
mkdir Arthropoda-Amyelois-transitella &&
cd Arthropoda-Amyelois-transitella &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/186/105/GCF_001186105.1_ASM118610v1/GCF_001186105.1_ASM118610v1_protein.faa.gz -O Arthropoda-Amyelois-transitella.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/186/105/GCF_001186105.1_ASM118610v1/GCF_001186105.1_ASM118610v1_genomic.gff.gz -O Arthropoda-Amyelois-transitella.gff.gz &&
cd .. &&
mkdir Arthropoda-Bombyx-mori &&
cd Arthropoda-Bombyx-mori &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/014/905/235/GCF_014905235.1_Bmori_2016v1.0/GCF_014905235.1_Bmori_2016v1.0_protein.faa.gz -O Arthropoda-Bombyx-mori.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/014/905/235/GCF_014905235.1_Bmori_2016v1.0/GCF_014905235.1_Bmori_2016v1.0_genomic.gff.gz -O Arthropoda-Bombyx-mori.gff.gz &&
cd .. &&
mkdir Arthropoda-Hyposmocoma-kahamanoa &&
cd Arthropoda-Hyposmocoma-kahamanoa &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/589/595/GCF_003589595.1_ASM358959v1/GCF_003589595.1_ASM358959v1_protein.faa.gz -O Arthropoda-Hyposmocoma-kahamanoa.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/589/595/GCF_003589595.1_ASM358959v1/GCF_003589595.1_ASM358959v1_genomic.gff.gz -O Arthropoda-Hyposmocoma-kahamanoa.gff.gz &&
cd .. &&
mkdir Arthropoda-Plutella-xylostella &&
cd Arthropoda-Plutella-xylostella &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/905/116/875/GCF_905116875.1_Haplomerged_assembly/GCF_905116875.1_Haplomerged_assembly_protein.faa.gz -O Arthropoda-Plutella-xylostella.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/905/116/875/GCF_905116875.1_Haplomerged_assembly/GCF_905116875.1_Haplomerged_assembly_genomic.gff.gz -O Arthropoda-Plutella-xylostella.gff.gz &&
cd .. &&
mkdir Arthropoda-Spodoptera-frugiperda- &&
cd Arthropoda-Spodoptera-frugiperda- &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/011/064/685/GCF_011064685.1_ZJU_Sfru_1.0/GCF_011064685.1_ZJU_Sfru_1.0_protein.faa.gz -O Arthropoda-Spodoptera-frugiperda-.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/011/064/685/GCF_011064685.1_ZJU_Sfru_1.0/GCF_011064685.1_ZJU_Sfru_1.0_genomic.gff.gz -O Arthropoda-Spodoptera-frugiperda-.gff.gz &&
cd .. &&
mkdir Arthropoda-Aricia-agestis &&
cd Arthropoda-Aricia-agestis &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/905/147/365/GCF_905147365.1_ilAriAges1.1/GCF_905147365.1_ilAriAges1.1_protein.faa.gz -O Arthropoda-Aricia-agestis.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/905/147/365/GCF_905147365.1_ilAriAges1.1/GCF_905147365.1_ilAriAges1.1_genomic.gff.gz -O Arthropoda-Aricia-agestis.gff.gz &&
cd .. &&
mkdir Arthropoda-Pararge-aegeria &&
cd Arthropoda-Pararge-aegeria &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/905/163/445/GCF_905163445.1_ilParAegt1.1/GCF_905163445.1_ilParAegt1.1_protein.faa.gz -O Arthropoda-Pararge-aegeria.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/905/163/445/GCF_905163445.1_ilParAegt1.1/GCF_905163445.1_ilParAegt1.1_genomic.gff.gz -O Arthropoda-Pararge-aegeria.gff.gz &&
cd .. &&
mkdir Arthropoda-Zerene-cesonia &&
cd Arthropoda-Zerene-cesonia &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/012/273/895/GCF_012273895.1_Zerene_cesonia_1.1/GCF_012273895.1_Zerene_cesonia_1.1_protein.faa.gz -O Arthropoda-Zerene-cesonia.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/012/273/895/GCF_012273895.1_Zerene_cesonia_1.1/GCF_012273895.1_Zerene_cesonia_1.1_genomic.gff.gz -O Arthropoda-Zerene-cesonia.gff.gz &&
cd .. &&
mkdir Arthropoda-Papilio-xuthus &&
cd Arthropoda-Papilio-xuthus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/836/235/GCF_000836235.1_Pxut_1.0/GCF_000836235.1_Pxut_1.0_protein.faa.gz -O Arthropoda-Papilio-xuthus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/836/235/GCF_000836235.1_Pxut_1.0/GCF_000836235.1_Pxut_1.0_genomic.gff.gz -O Arthropoda-Papilio-xuthus.gff.gz &&
cd .. &&
mkdir Arthropoda-Danaus-plexippus &&
cd Arthropoda-Danaus-plexippus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/731/565/GCF_009731565.1_Dplex_v4/GCF_009731565.1_Dplex_v4_protein.faa.gz -O Arthropoda-Danaus-plexippus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/731/565/GCF_009731565.1_Dplex_v4/GCF_009731565.1_Dplex_v4_genomic.gff.gz -O Arthropoda-Danaus-plexippus.gff.gz &&
cd .. &&
mkdir Chordata-Ornithorhynchus-anatinus &&
cd Chordata-Ornithorhynchus-anatinus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/004/115/215/GCF_004115215.2_mOrnAna1.pri.v4/GCF_004115215.2_mOrnAna1.pri.v4_protein.faa.gz -O Chordata-Ornithorhynchus-anatinus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/004/115/215/GCF_004115215.2_mOrnAna1.pri.v4/GCF_004115215.2_mOrnAna1.pri.v4_genomic.gff.gz -O Chordata-Ornithorhynchus-anatinus.gff.gz &&
cd .. &&
mkdir Chordata-Phascolarctos-cinereus &&
cd Chordata-Phascolarctos-cinereus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/099/425/GCF_002099425.1_phaCin_unsw_v4.1/GCF_002099425.1_phaCin_unsw_v4.1_protein.faa.gz -O Chordata-Phascolarctos-cinereus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/099/425/GCF_002099425.1_phaCin_unsw_v4.1/GCF_002099425.1_phaCin_unsw_v4.1_genomic.gff.gz -O Chordata-Phascolarctos-cinereus.gff.gz &&
cd .. &&
mkdir Chordata-Vombatus-ursinus &&
cd Chordata-Vombatus-ursinus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/900/497/805/GCF_900497805.2_bare-nosed_wombat_genome_assembly/GCF_900497805.2_bare-nosed_wombat_genome_assembly_protein.faa.gz -O Chordata-Vombatus-ursinus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/900/497/805/GCF_900497805.2_bare-nosed_wombat_genome_assembly/GCF_900497805.2_bare-nosed_wombat_genome_assembly_genomic.gff.gz -O Chordata-Vombatus-ursinus.gff.gz &&
cd .. &&
mkdir Chordata-Dromiciops-gliroides &&
cd Chordata-Dromiciops-gliroides &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/019/393/635/GCF_019393635.1_mDroGli1.pri/GCF_019393635.1_mDroGli1.pri_protein.faa.gz -O Chordata-Dromiciops-gliroides.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/019/393/635/GCF_019393635.1_mDroGli1.pri/GCF_019393635.1_mDroGli1.pri_genomic.gff.gz -O Chordata-Dromiciops-gliroides.gff.gz &&
cd .. &&
mkdir Chordata-Monodelphis-domestica &&
cd Chordata-Monodelphis-domestica &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/002/295/GCF_000002295.2_MonDom5/GCF_000002295.2_MonDom5_protein.faa.gz -O Chordata-Monodelphis-domestica.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/002/295/GCF_000002295.2_MonDom5/GCF_000002295.2_MonDom5_genomic.gff.gz -O Chordata-Monodelphis-domestica.gff.gz &&
cd .. &&
mkdir Chordata-Sarcophilus-harrisii &&
cd Chordata-Sarcophilus-harrisii &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/902/635/505/GCF_902635505.1_mSarHar1.11/GCF_902635505.1_mSarHar1.11_protein.faa.gz -O Chordata-Sarcophilus-harrisii.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/902/635/505/GCF_902635505.1_mSarHar1.11/GCF_902635505.1_mSarHar1.11_genomic.gff.gz -O Chordata-Sarcophilus-harrisii.gff.gz &&
cd .. &&
mkdir Chordata-Loxodonta-africana &&
cd Chordata-Loxodonta-africana &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/905/GCF_000001905.1_Loxafr3.0/GCF_000001905.1_Loxafr3.0_protein.faa.gz -O Chordata-Loxodonta-africana.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/905/GCF_000001905.1_Loxafr3.0/GCF_000001905.1_Loxafr3.0_genomic.gff.gz -O Chordata-Loxodonta-africana.gff.gz &&
cd .. &&
mkdir Chordata-Orycteropus-afer-afer &&
cd Chordata-Orycteropus-afer-afer &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/298/275/GCF_000298275.1_OryAfe1.0/GCF_000298275.1_OryAfe1.0_protein.faa.gz -O Chordata-Orycteropus-afer-afer.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/298/275/GCF_000298275.1_OryAfe1.0/GCF_000298275.1_OryAfe1.0_genomic.gff.gz -O Chordata-Orycteropus-afer-afer.gff.gz &&
cd .. &&
mkdir Chordata-Trichechus-manatus-latirostris &&
cd Chordata-Trichechus-manatus-latirostris &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/243/295/GCF_000243295.1_TriManLat1.0/GCF_000243295.1_TriManLat1.0_protein.faa.gz -O Chordata-Trichechus-manatus-latirostris.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/243/295/GCF_000243295.1_TriManLat1.0/GCF_000243295.1_TriManLat1.0_genomic.gff.gz -O Chordata-Trichechus-manatus-latirostris.gff.gz &&
cd .. &&
mkdir Chordata-Dasypus-novemcinctus &&
cd Chordata-Dasypus-novemcinctus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/208/655/GCF_000208655.1_Dasnov3.0/GCF_000208655.1_Dasnov3.0_protein.faa.gz -O Chordata-Dasypus-novemcinctus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/208/655/GCF_000208655.1_Dasnov3.0/GCF_000208655.1_Dasnov3.0_genomic.gff.gz -O Chordata-Dasypus-novemcinctus.gff.gz &&
cd .. &&
mkdir Chordata-Choloepus-didactylus &&
cd Chordata-Choloepus-didactylus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/015/220/235/GCF_015220235.1_mChoDid1.pri/GCF_015220235.1_mChoDid1.pri_protein.faa.gz -O Chordata-Choloepus-didactylus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/015/220/235/GCF_015220235.1_mChoDid1.pri/GCF_015220235.1_mChoDid1.pri_genomic.gff.gz -O Chordata-Choloepus-didactylus.gff.gz &&
cd .. &&
mkdir Chordata-Tupaia-chinensis &&
cd Chordata-Tupaia-chinensis &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/334/495/GCF_000334495.1_TupChi_1.0/GCF_000334495.1_TupChi_1.0_protein.faa.gz -O Chordata-Tupaia-chinensis.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/334/495/GCF_000334495.1_TupChi_1.0/GCF_000334495.1_TupChi_1.0_genomic.gff.gz -O Chordata-Tupaia-chinensis.gff.gz &&
cd .. &&
mkdir Chordata-Oryctolagus-cuniculus &&
cd Chordata-Oryctolagus-cuniculus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/003/625/GCF_000003625.3_OryCun2.0/GCF_000003625.3_OryCun2.0_protein.faa.gz -O Chordata-Oryctolagus-cuniculus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/003/625/GCF_000003625.3_OryCun2.0/GCF_000003625.3_OryCun2.0_genomic.gff.gz -O Chordata-Oryctolagus-cuniculus.gff.gz &&
cd .. &&
mkdir Chordata-Galeopterus-variegatus &&
cd Chordata-Galeopterus-variegatus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/696/425/GCF_000696425.1_G_variegatus-3.0.2/GCF_000696425.1_G_variegatus-3.0.2_protein.faa.gz -O Chordata-Galeopterus-variegatus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/696/425/GCF_000696425.1_G_variegatus-3.0.2/GCF_000696425.1_G_variegatus-3.0.2_genomic.gff.gz -O Chordata-Galeopterus-variegatus.gff.gz &&
cd .. &&
mkdir Chordata-Carlito-syrichta &&
cd Chordata-Carlito-syrichta &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/164/805/GCF_000164805.1_Tarsius_syrichta-2.0.1/GCF_000164805.1_Tarsius_syrichta-2.0.1_protein.faa.gz -O Chordata-Carlito-syrichta.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/164/805/GCF_000164805.1_Tarsius_syrichta-2.0.1/GCF_000164805.1_Tarsius_syrichta-2.0.1_genomic.gff.gz -O Chordata-Carlito-syrichta.gff.gz &&
cd .. &&
mkdir Chordata-Microcebus-murinus &&
cd Chordata-Microcebus-murinus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/165/445/GCF_000165445.2_Mmur_3.0/GCF_000165445.2_Mmur_3.0_protein.faa.gz -O Chordata-Microcebus-murinus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/165/445/GCF_000165445.2_Mmur_3.0/GCF_000165445.2_Mmur_3.0_genomic.gff.gz -O Chordata-Microcebus-murinus.gff.gz &&
cd .. &&
mkdir Chordata-Rousettus-aegyptiacus &&
cd Chordata-Rousettus-aegyptiacus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/014/176/215/GCF_014176215.1_mRouAeg1.p/GCF_014176215.1_mRouAeg1.p_protein.faa.gz -O Chordata-Rousettus-aegyptiacus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/014/176/215/GCF_014176215.1_mRouAeg1.p/GCF_014176215.1_mRouAeg1.p_genomic.gff.gz -O Chordata-Rousettus-aegyptiacus.gff.gz &&
cd .. &&
mkdir Chordata-Hipposideros-armiger &&
cd Chordata-Hipposideros-armiger &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/890/085/GCF_001890085.1_ASM189008v1/GCF_001890085.1_ASM189008v1_protein.faa.gz -O Chordata-Hipposideros-armiger.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/890/085/GCF_001890085.1_ASM189008v1/GCF_001890085.1_ASM189008v1_genomic.gff.gz -O Chordata-Hipposideros-armiger.gff.gz &&
cd .. &&
mkdir Chordata-Rhinolophus-ferrumequinum &&
cd Chordata-Rhinolophus-ferrumequinum &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/004/115/265/GCF_004115265.1_mRhiFer1_v1.p/GCF_004115265.1_mRhiFer1_v1.p_protein.faa.gz -O Chordata-Rhinolophus-ferrumequinum.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/004/115/265/GCF_004115265.1_mRhiFer1_v1.p/GCF_004115265.1_mRhiFer1_v1.p_genomic.gff.gz -O Chordata-Rhinolophus-ferrumequinum.gff.gz &&
cd .. &&
mkdir Chordata-Phyllostomus-discolor &&
cd Chordata-Phyllostomus-discolor &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/004/126/475/GCF_004126475.2_mPhyDis1.pri.v3/GCF_004126475.2_mPhyDis1.pri.v3_protein.faa.gz -O Chordata-Phyllostomus-discolor.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/004/126/475/GCF_004126475.2_mPhyDis1.pri.v3/GCF_004126475.2_mPhyDis1.pri.v3_genomic.gff.gz -O Chordata-Phyllostomus-discolor.gff.gz &&
cd .. &&
mkdir Chordata-Molossus-molossus &&
cd Chordata-Molossus-molossus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/014/108/415/GCF_014108415.1_mMolMol1.p/GCF_014108415.1_mMolMol1.p_protein.faa.gz -O Chordata-Molossus-molossus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/014/108/415/GCF_014108415.1_mMolMol1.p/GCF_014108415.1_mMolMol1.p_genomic.gff.gz -O Chordata-Molossus-molossus.gff.gz &&
cd .. &&
mkdir Chordata-Miniopterus-natalensis &&
cd Chordata-Miniopterus-natalensis &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/595/765/GCF_001595765.1_Mnat.v1/GCF_001595765.1_Mnat.v1_protein.faa.gz -O Chordata-Miniopterus-natalensis.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/595/765/GCF_001595765.1_Mnat.v1/GCF_001595765.1_Mnat.v1_genomic.gff.gz -O Chordata-Miniopterus-natalensis.gff.gz &&
cd .. &&
mkdir Chordata-Pipistrellus-kuhlii &&
cd Chordata-Pipistrellus-kuhlii &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/014/108/245/GCF_014108245.1_mPipKuh1.p/GCF_014108245.1_mPipKuh1.p_protein.faa.gz -O Chordata-Pipistrellus-kuhlii.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/014/108/245/GCF_014108245.1_mPipKuh1.p/GCF_014108245.1_mPipKuh1.p_genomic.gff.gz -O Chordata-Pipistrellus-kuhlii.gff.gz &&
cd .. &&
mkdir Chordata-Felis-catus &&
cd Chordata-Felis-catus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/018/350/175/GCF_018350175.1_F.catus_Fca126_mat1.0/GCF_018350175.1_F.catus_Fca126_mat1.0_protein.faa.gz -O Chordata-Felis-catus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/018/350/175/GCF_018350175.1_F.catus_Fca126_mat1.0/GCF_018350175.1_F.catus_Fca126_mat1.0_genomic.gff.gz -O Chordata-Felis-catus.gff.gz &&
cd .. &&
mkdir Chordata-Manis-pentadactyla &&
cd Chordata-Manis-pentadactyla &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/014/570/555/GCF_014570555.1_YNU_ManPten_2.0/GCF_014570555.1_YNU_ManPten_2.0_protein.faa.gz -O Chordata-Manis-pentadactyla.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/014/570/555/GCF_014570555.1_YNU_ManPten_2.0/GCF_014570555.1_YNU_ManPten_2.0_genomic.gff.gz -O Chordata-Manis-pentadactyla.gff.gz &&
cd .. &&
mkdir Chordata-Phoca-vitulina &&
cd Chordata-Phoca-vitulina &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/004/348/235/GCF_004348235.1_GSC_HSeal_1.0/GCF_004348235.1_GSC_HSeal_1.0_protein.faa.gz -O Chordata-Phoca-vitulina.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/004/348/235/GCF_004348235.1_GSC_HSeal_1.0/GCF_004348235.1_GSC_HSeal_1.0_genomic.gff.gz -O Chordata-Phoca-vitulina.gff.gz &&
cd .. &&
mkdir Chordata-Ailuropoda-melanoleuca &&
cd Chordata-Ailuropoda-melanoleuca &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/007/445/GCF_002007445.1_ASM200744v2/GCF_002007445.1_ASM200744v2_protein.faa.gz -O Chordata-Ailuropoda-melanoleuca.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/007/445/GCF_002007445.1_ASM200744v2/GCF_002007445.1_ASM200744v2_genomic.gff.gz -O Chordata-Ailuropoda-melanoleuca.gff.gz &&
cd .. &&
mkdir Chordata-Canis-lupus-familiaris &&
cd Chordata-Canis-lupus-familiaris &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/014/441/545/GCF_014441545.1_ROS_Cfam_1.0/GCF_014441545.1_ROS_Cfam_1.0_protein.faa.gz -O Chordata-Canis-lupus-familiaris.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/014/441/545/GCF_014441545.1_ROS_Cfam_1.0/GCF_014441545.1_ROS_Cfam_1.0_genomic.gff.gz -O Chordata-Canis-lupus-familiaris.gff.gz &&
cd .. &&
mkdir Chordata-Equus-caballus &&
cd Chordata-Equus-caballus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/863/925/GCF_002863925.1_EquCab3.0/GCF_002863925.1_EquCab3.0_protein.faa.gz -O Chordata-Equus-caballus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/863/925/GCF_002863925.1_EquCab3.0/GCF_002863925.1_EquCab3.0_genomic.gff.gz -O Chordata-Equus-caballus.gff.gz &&
cd .. &&
mkdir Chordata-Camelus-dromedarius &&
cd Chordata-Camelus-dromedarius &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/803/125/GCF_000803125.2_CamDro3/GCF_000803125.2_CamDro3_protein.faa.gz -O Chordata-Camelus-dromedarius.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/803/125/GCF_000803125.2_CamDro3/GCF_000803125.2_CamDro3_genomic.gff.gz -O Chordata-Camelus-dromedarius.gff.gz &&
cd .. &&
mkdir Chordata-Capra-hircus &&
cd Chordata-Capra-hircus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/704/415/GCF_001704415.1_ARS1/GCF_001704415.1_ARS1_protein.faa.gz -O Chordata-Capra-hircus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/704/415/GCF_001704415.1_ARS1/GCF_001704415.1_ARS1_genomic.gff.gz -O Chordata-Capra-hircus.gff.gz &&
cd .. &&
mkdir Chordata-Sus-scrofa- &&
cd Chordata-Sus-scrofa- &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/003/025/GCF_000003025.6_Sscrofa11.1/GCF_000003025.6_Sscrofa11.1_protein.faa.gz -O Chordata-Sus-scrofa-.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/003/025/GCF_000003025.6_Sscrofa11.1/GCF_000003025.6_Sscrofa11.1_genomic.gff.gz -O Chordata-Sus-scrofa-.gff.gz &&
cd .. &&
mkdir Chordata-Bos-taurus &&
cd Chordata-Bos-taurus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/263/795/GCF_002263795.1_ARS-UCD1.2/GCF_002263795.1_ARS-UCD1.2_protein.faa.gz -O Chordata-Bos-taurus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/263/795/GCF_002263795.1_ARS-UCD1.2/GCF_002263795.1_ARS-UCD1.2_genomic.gff.gz -O Chordata-Bos-taurus.gff.gz &&
cd .. &&
mkdir Chordata-Balaenoptera-musculus &&
cd Chordata-Balaenoptera-musculus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/873/245/GCF_009873245.2_mBalMus1.pri.v3/GCF_009873245.2_mBalMus1.pri.v3_protein.faa.gz -O Chordata-Balaenoptera-musculus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/873/245/GCF_009873245.2_mBalMus1.pri.v3/GCF_009873245.2_mBalMus1.pri.v3_genomic.gff.gz -O Chordata-Balaenoptera-musculus.gff.gz &&
cd .. &&
mkdir Chordata-Balaenoptera-acutorostrata-scammoni &&
cd Chordata-Balaenoptera-acutorostrata-scammoni &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/493/695/GCF_000493695.1_BalAcu1.0/GCF_000493695.1_BalAcu1.0_protein.faa.gz -O Chordata-Balaenoptera-acutorostrata-scammoni.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/493/695/GCF_000493695.1_BalAcu1.0/GCF_000493695.1_BalAcu1.0_genomic.gff.gz -O Chordata-Balaenoptera-acutorostrata-scammoni.gff.gz &&
cd .. &&
mkdir Chordata-Balaenoptera-physalus &&
cd Chordata-Balaenoptera-physalus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/008/795/845/GCA_008795845.1_Baphy/GCA_008795845.1_Baphy_protein.faa.gz -O Chordata-Balaenoptera-physalus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/008/795/845/GCA_008795845.1_Baphy/GCA_008795845.1_Baphy_genomic.gff.gz -O Chordata-Balaenoptera-physalus.gff.gz &&
cd .. &&
mkdir Chordata-Neophocaena-asiaeorientalis-asiaeorientalis &&
cd Chordata-Neophocaena-asiaeorientalis-asiaeorientalis &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/031/525/GCF_003031525.2_Neophocaena_asiaeorientalis_V1/GCF_003031525.2_Neophocaena_asiaeorientalis_V1_protein.faa.gz -O Chordata-Neophocaena-asiaeorientalis-asiaeorientalis.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/031/525/GCF_003031525.2_Neophocaena_asiaeorientalis_V1/GCF_003031525.2_Neophocaena_asiaeorientalis_V1_genomic.gff.gz -O Chordata-Neophocaena-asiaeorientalis-asiaeorientalis.gff.gz &&
cd .. &&
mkdir Chordata-Phocoena-sinus &&
cd Chordata-Phocoena-sinus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/008/692/025/GCF_008692025.1_mPhoSin1.pri/GCF_008692025.1_mPhoSin1.pri_protein.faa.gz -O Chordata-Phocoena-sinus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/008/692/025/GCF_008692025.1_mPhoSin1.pri/GCF_008692025.1_mPhoSin1.pri_genomic.gff.gz -O Chordata-Phocoena-sinus.gff.gz &&
cd .. &&
mkdir Chordata-Lagenorhynchus-obliquidens &&
cd Chordata-Lagenorhynchus-obliquidens &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/676/395/GCF_003676395.1_ASM367639v1/GCF_003676395.1_ASM367639v1_protein.faa.gz -O Chordata-Lagenorhynchus-obliquidens.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/676/395/GCF_003676395.1_ASM367639v1/GCF_003676395.1_ASM367639v1_genomic.gff.gz -O Chordata-Lagenorhynchus-obliquidens.gff.gz &&
cd .. &&
mkdir Chordata-Pontoporia-blainvillei &&
cd Chordata-Pontoporia-blainvillei &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/011/754/075/GCA_011754075.1_ASM1175407v1/GCA_011754075.1_ASM1175407v1_protein.faa.gz -O Chordata-Pontoporia-blainvillei.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/011/754/075/GCA_011754075.1_ASM1175407v1/GCA_011754075.1_ASM1175407v1_genomic.gff.gz -O Chordata-Pontoporia-blainvillei.gff.gz &&
cd .. &&
mkdir Chordata-Globicephala-melas &&
cd Chordata-Globicephala-melas &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/006/547/405/GCF_006547405.1_ASM654740v1/GCF_006547405.1_ASM654740v1_protein.faa.gz -O Chordata-Globicephala-melas.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/006/547/405/GCF_006547405.1_ASM654740v1/GCF_006547405.1_ASM654740v1_genomic.gff.gz -O Chordata-Globicephala-melas.gff.gz &&
cd .. &&
mkdir Chordata-Lipotes-vexillifer &&
cd Chordata-Lipotes-vexillifer &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/442/215/GCF_000442215.1_Lipotes_vexillifer_v1/GCF_000442215.1_Lipotes_vexillifer_v1_protein.faa.gz -O Chordata-Lipotes-vexillifer.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/442/215/GCF_000442215.1_Lipotes_vexillifer_v1/GCF_000442215.1_Lipotes_vexillifer_v1_genomic.gff.gz -O Chordata-Lipotes-vexillifer.gff.gz &&
cd .. &&
mkdir Chordata-Orcinus-orca &&
cd Chordata-Orcinus-orca &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/331/955/GCF_000331955.2_Oorc_1.1/GCF_000331955.2_Oorc_1.1_protein.faa.gz -O Chordata-Orcinus-orca.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/331/955/GCF_000331955.2_Oorc_1.1/GCF_000331955.2_Oorc_1.1_genomic.gff.gz -O Chordata-Orcinus-orca.gff.gz &&
cd .. &&
mkdir Chordata-Delphinapterus-leucas &&
cd Chordata-Delphinapterus-leucas &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/288/925/GCF_002288925.2_ASM228892v3/GCF_002288925.2_ASM228892v3_protein.faa.gz -O Chordata-Delphinapterus-leucas.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/288/925/GCF_002288925.2_ASM228892v3/GCF_002288925.2_ASM228892v3_genomic.gff.gz -O Chordata-Delphinapterus-leucas.gff.gz &&
cd .. &&
mkdir Chordata-Tursiops-truncatus &&
cd Chordata-Tursiops-truncatus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/011/762/595/GCF_011762595.1_mTurTru1.mat.Y/GCF_011762595.1_mTurTru1.mat.Y_protein.faa.gz -O Chordata-Tursiops-truncatus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/011/762/595/GCF_011762595.1_mTurTru1.mat.Y/GCF_011762595.1_mTurTru1.mat.Y_genomic.gff.gz -O Chordata-Tursiops-truncatus.gff.gz &&
cd .. &&
mkdir Chordata-Monodon-monoceros &&
cd Chordata-Monodon-monoceros &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/005/190/385/GCF_005190385.1_NGI_Narwhal_1/GCF_005190385.1_NGI_Narwhal_1_protein.faa.gz -O Chordata-Monodon-monoceros.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/005/190/385/GCF_005190385.1_NGI_Narwhal_1/GCF_005190385.1_NGI_Narwhal_1_genomic.gff.gz -O Chordata-Monodon-monoceros.gff.gz &&
cd .. &&
mkdir Chordata-Physeter-catodon &&
cd Chordata-Physeter-catodon &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/837/175/GCF_002837175.2_ASM283717v2/GCF_002837175.2_ASM283717v2_protein.faa.gz -O Chordata-Physeter-catodon.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/837/175/GCF_002837175.2_ASM283717v2/GCF_002837175.2_ASM283717v2_genomic.gff.gz -O Chordata-Physeter-catodon.gff.gz &&
cd .. &&
mkdir Mollusca-Elysia-marginata- &&
cd Mollusca-Elysia-marginata- &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/019/649/035/GCA_019649035.1_Ema_v1/GCA_019649035.1_Ema_v1_protein.faa.gz -O Mollusca-Elysia-marginata-.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/019/649/035/GCA_019649035.1_Ema_v1/GCA_019649035.1_Ema_v1_genomic.gff.gz -O Mollusca-Elysia-marginata-.gff.gz &&
cd .. &&
mkdir Mollusca-Elysia-chlorotica &&
cd Mollusca-Elysia-chlorotica &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/991/915/GCA_003991915.1_ElyChl2.0/GCA_003991915.1_ElyChl2.0_protein.faa.gz -O Mollusca-Elysia-chlorotica.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/991/915/GCA_003991915.1_ElyChl2.0/GCA_003991915.1_ElyChl2.0_genomic.gff.gz -O Mollusca-Elysia-chlorotica.gff.gz &&
cd .. &&
mkdir Mollusca-Mytilus-coruscus &&
cd Mollusca-Mytilus-coruscus &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/011/752/425/GCA_011752425.2_MCOR1.1/GCA_011752425.2_MCOR1.1_protein.faa.gz -O Mollusca-Mytilus-coruscus.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/011/752/425/GCA_011752425.2_MCOR1.1/GCA_011752425.2_MCOR1.1_genomic.gff.gz -O Mollusca-Mytilus-coruscus.gff.gz &&
cd .. &&
mkdir Mollusca-Mytilus-galloprovincialis &&
cd Mollusca-Mytilus-galloprovincialis &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/900/618/805/GCA_900618805.1_MGAL_10/GCA_900618805.1_MGAL_10_protein.faa.gz -O Mollusca-Mytilus-galloprovincialis.aa.gz &&
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/900/618/805/GCA_900618805.1_MGAL_10/GCA_900618805.1_MGAL_10_genomic.gff.g -O Mollusca-Mytilus-galloprovincialis.gff.gz &&
cd .. &&
echo 
