#! python

input_list = open( 'output/4-list-short-summaries', 'r' )
output_cp = open( '006-cp-short-summaries', 'w' )

# short_summary.specific.metazoa_odb10.3-busco_metazoa-Chordata-Mammalia-Primates-Hominidae-Homo-sapiens-9606-T1.txt
# output/6-busco-short-summaries

for next_line in input_list:
    short_summary_path = next_line[ :-1 ]
    short_summary = short_summary_path.split( '/' )[ -1 ]
    info_dot = short_summary.split( '.' )
    info_dash = info_dot[ 3 ].split( '-' )
    phylum = info_dash[ 2 ]
    genus = info_dash[ 6 ]
    species = info_dash[ 7 ]
    pHgspp = phylum + '-' + genus + '-' + species
    short_summary_clean = 'busco-metazoa-short-summary-' + '.'.join( info_dot )
    output = 'cp ' + short_summary_path + ' output/6-output-busco-short-summaries/' + short_summary + ' \n'
    output_cp.write( output )

input_list.close()
output_cp.close()

    
    
