#! python

# input_list
# 11-projectdb-Homo-sapiens-cgs-AA.dmnd

input_list = open( 'output/13-list-blastp-annotated-rgs-genomes', 'r' )
output_command = open( '015-blastp-hits_X_RGS-genomes-blast-suite-2.12.0', 'w' )

output = '#! /bin/bash\n'
output_command.write( output )

for next_line in input_list:

    db_path = next_line[ :-1 ]
    info = db_path.split( '-' )
    genome = info[ -3 ] + '-' + info[ -2 ]

    output =  'blastp -db ' + db_path  + ' -outfmt 6 -out output/15-blastp-report-blastp_hits_X_RGS-genome-' + genome + '  -max_target_seqs 1 -max_hsps 1 -query output/7-blastp-hits.fasta -matrix BLOSUM45 -evalue 1e-3 -num_threads 30\n'
 
    output_command.write( output )

output = 'echo\n'
output_command.write( output )

input_list.close()
output_command.close()
