#! python

input_list = open( '001-list-othersdb-source-info.tsv', 'r' )
output_commands = open( '002-wget-othersdb-at-ncbi-genome', 'w' )
output_map_fasta = open( '1-map-fasta-source-to-phgspp', 'w' )
output_map_gff = open( '1-map-gff-source-to-phgspp', 'w' )

for next_line in input_list:

    info = next_line[ :-1 ].split( '\t' )
    phylum = info[ 0 ]
    genus_spp = info[ 1 ].split( ' ' )
    phgspp = phylum + '-' + '-'.join( genus_spp )
    assembly_fasta = info[ 2 ]
    gff = info[ 3 ]

    info_fasta = '.'.join( assembly_fasta.split( '.' )[ :-2 ] )
    source_fasta = info_fasta.split( '/' )[ -1 ]
    output = phgspp + '.aa\t' + source_fasta
    output_map_fasta.write( output )
    
    info_gff = '.'.join( gff.split( '.' )[ :-2 ] )
    source_gff = info_gff.split( '/' )[ -1 ]
    output = phgspp + '.gff\t' + source_gff
    output_map_gff.write( output )
    
    output = 'mkdir ' + phgspp + ' &&\n' + 'cd ' + phgspp + ' &&\n'
    output_commands.write( output )

    # assumes .gz files from source
    output = 'wget ' + assembly_fasta + ' -O ' + phgspp + '.aa.gz &&\nwget ' + gff + ' -O ' + phgspp + '.gff.gz &&\n'
    output_commands.write( output )
        

    output = 'cd .. &&\n'
    output_commands.write( output )

output = 'echo \n'
output_commands.write( output )

input_list.close()
output_commands.close()
